USE [Mentor]
GO
/****** Object:  Table [dbo].[SYS_CITY]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_CITY](
	[CITY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CITY_NAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_SYS_CITY] PRIMARY KEY CLUSTERED 
(
	[CITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_COMPETENCE]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_COMPETENCE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TUTOR_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[LEVEL_ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
 CONSTRAINT [PK_SYS_TUTOR_TO_SUBJECT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_EDU_LEVEL]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_EDU_LEVEL](
	[EDU_LEVEL_ID] [int] NOT NULL,
	[EDU_LEVEL_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_EDU_LEVEL] PRIMARY KEY CLUSTERED 
(
	[EDU_LEVEL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SYS_EDU_LEVEL] UNIQUE NONCLUSTERED 
(
	[EDU_LEVEL_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_ELEMENT]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_ELEMENT](
	[ELEMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ELEMENT_NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
 CONSTRAINT [PK_ELEMENT] PRIMARY KEY CLUSTERED 
(
	[ELEMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_ELEMENT] UNIQUE NONCLUSTERED 
(
	[ELEMENT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_GROUP]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_GROUP](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_GROUP] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_LESSON]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_LESSON](
	[LESSON_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[LESSON_STATUS_ID] [int] NOT NULL,
	[TUTOR_ID] [int] NOT NULL,
	[STUDENT_ID] [int] NOT NULL,
	[DATE_START] [datetime] NOT NULL,
	[DATE_STOP] [datetime] NOT NULL,
	[RATING_ID] [int] NOT NULL,
 CONSTRAINT [PK_SYS_LECCON] PRIMARY KEY CLUSTERED 
(
	[LESSON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_LESSON_STATUS]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_LESSON_STATUS](
	[LESSON_STATUS_ID] [int] IDENTITY(1,1) NOT NULL,
	[LESSON_STATUS_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_LESSON_STATUS] PRIMARY KEY CLUSTERED 
(
	[LESSON_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_LEVEL]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_LEVEL](
	[LEVEL_ID] [int] IDENTITY(1,1) NOT NULL,
	[LEVEL_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_LEVEL] PRIMARY KEY CLUSTERED 
(
	[LEVEL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SYS_LEVEL] UNIQUE NONCLUSTERED 
(
	[LEVEL_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_PERMISSION]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_PERMISSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_ID] [int] NOT NULL,
	[ELEMENT_ID] [int] NOT NULL,
 CONSTRAINT [PK_USER_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_USER_PERMISSION] UNIQUE NONCLUSTERED 
(
	[GROUP_ID] ASC,
	[ELEMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_RATING]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_RATING](
	[RATING_ID] [int] IDENTITY(1,1) NOT NULL,
	[RATING_VALUE] [int] NOT NULL,
	[RATING_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_RATING] PRIMARY KEY CLUSTERED 
(
	[RATING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_SUBJECT]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_SUBJECT](
	[SUBJECT_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBJECT_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_SUBJECT] PRIMARY KEY CLUSTERED 
(
	[SUBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SYS_SUBJECT] UNIQUE NONCLUSTERED 
(
	[SUBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_USER]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USER](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_FULLNAME] [nvarchar](100) NOT NULL,
	[USER_NICKNAME] [nvarchar](50) NOT NULL,
	[USER_EMAIL] [nvarchar](100) NOT NULL,
	[USER_PHONE] [nvarchar](50) NULL,
	[USER_PASS] [nvarchar](50) NOT NULL,
	[USER_DESCRIPTION] [nvarchar](250) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[GROUP_ID] [int] NOT NULL,
	[WORK_TYPE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SYS_USER] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_USER_TO_AREA]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USER_TO_CITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[CITY_ID] [int] NOT NULL,
 CONSTRAINT [PK_SYS_USER_TO_CITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SYS_USER_TO_AREA] UNIQUE NONCLUSTERED 
(
	[USER_ID] ASC,
	[AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_USER_TO_RATING]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USER_TO_RATING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TUTOR_ID] [int] NOT NULL,
	[STUDENT_ID] [int] NOT NULL,
	[RATING_ID] [int] NOT NULL,
	[DATE_TIME] [datetime] NOT NULL,
 CONSTRAINT [PK_SYS_USER_TO_RATING] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SYS_USER_TO_RATING] UNIQUE NONCLUSTERED 
(
	[TUTOR_ID] ASC,
	[STUDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_USER_TO_SPECIALITY]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USER_TO_SPECIALITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[EDU_LEVEL_ID] [int] NOT NULL,
	[SPECIALITY] [nvarchar](1000) NULL,
 CONSTRAINT [PK_SYS_USER_TO_SPECIALITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYS_WORK_TYPE]    Script Date: 2023-06-21 01:02:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_WORK_TYPE](
	[WORK_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[WORK_TYPE_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SYS_WORK_TYPE] PRIMARY KEY CLUSTERED 
(
	[WORK_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYS_USER] ADD  CONSTRAINT [DF_SYS_USER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[SYS_COMPETENCE]  WITH CHECK ADD  CONSTRAINT [FK_SYS_COMPETENCE_SYS_LEVEL] FOREIGN KEY([LEVEL_ID])
REFERENCES [dbo].[SYS_LEVEL] ([LEVEL_ID])
GO
ALTER TABLE [dbo].[SYS_COMPETENCE] CHECK CONSTRAINT [FK_SYS_COMPETENCE_SYS_LEVEL]
GO
ALTER TABLE [dbo].[SYS_COMPETENCE]  WITH CHECK ADD  CONSTRAINT [FK_SYS_COMPETENCE_SYS_SUBJECT] FOREIGN KEY([SUBJECT_ID])
REFERENCES [dbo].[SYS_SUBJECT] ([SUBJECT_ID])
GO
ALTER TABLE [dbo].[SYS_COMPETENCE] CHECK CONSTRAINT [FK_SYS_COMPETENCE_SYS_SUBJECT]
GO
ALTER TABLE [dbo].[SYS_COMPETENCE]  WITH CHECK ADD  CONSTRAINT [FK_SYS_COMPETENCE_SYS_USER] FOREIGN KEY([TUTOR_ID])
REFERENCES [dbo].[SYS_USER] ([USER_ID])
GO
ALTER TABLE [dbo].[SYS_COMPETENCE] CHECK CONSTRAINT [FK_SYS_COMPETENCE_SYS_USER]
GO
ALTER TABLE [dbo].[SYS_LESSON]  WITH CHECK ADD  CONSTRAINT [FK_SYS_LESSON_SYS_LESSON_STATUS] FOREIGN KEY([LESSON_STATUS_ID])
REFERENCES [dbo].[SYS_LESSON_STATUS] ([LESSON_STATUS_ID])
GO
ALTER TABLE [dbo].[SYS_LESSON] CHECK CONSTRAINT [FK_SYS_LESSON_SYS_LESSON_STATUS]
GO
ALTER TABLE [dbo].[SYS_LESSON]  WITH CHECK ADD  CONSTRAINT [FK_SYS_LESSON_SYS_SUBJECT] FOREIGN KEY([SUBJECT_ID])
REFERENCES [dbo].[SYS_SUBJECT] ([SUBJECT_ID])
GO
ALTER TABLE [dbo].[SYS_LESSON] CHECK CONSTRAINT [FK_SYS_LESSON_SYS_SUBJECT]
GO
ALTER TABLE [dbo].[SYS_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_SYS_PERMISSION_SYS_ELEMENT] FOREIGN KEY([ELEMENT_ID])
REFERENCES [dbo].[SYS_ELEMENT] ([ELEMENT_ID])
GO
ALTER TABLE [dbo].[SYS_PERMISSION] CHECK CONSTRAINT [FK_SYS_PERMISSION_SYS_ELEMENT]
GO
ALTER TABLE [dbo].[SYS_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_SYS_PERMISSION_SYS_GROUP] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[SYS_GROUP] ([GROUP_ID])
GO
ALTER TABLE [dbo].[SYS_PERMISSION] CHECK CONSTRAINT [FK_SYS_PERMISSION_SYS_GROUP]
GO
ALTER TABLE [dbo].[SYS_USER]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_SYS_GROUP] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[SYS_GROUP] ([GROUP_ID])
GO
ALTER TABLE [dbo].[SYS_USER] CHECK CONSTRAINT [FK_SYS_USER_SYS_GROUP]
GO
ALTER TABLE [dbo].[SYS_USER]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_SYS_WORK_TYPE] FOREIGN KEY([WORK_TYPE_ID])
REFERENCES [dbo].[SYS_WORK_TYPE] ([WORK_TYPE_ID])
GO
ALTER TABLE [dbo].[SYS_USER] CHECK CONSTRAINT [FK_SYS_USER_SYS_WORK_TYPE]
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_RATING] FOREIGN KEY([RATING_ID])
REFERENCES [dbo].[SYS_RATING] ([RATING_ID])
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING] CHECK CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_RATING]
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_USER_STUDENT] FOREIGN KEY([STUDENT_ID])
REFERENCES [dbo].[SYS_USER] ([USER_ID])
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING] CHECK CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_USER_STUDENT]
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_USER_TUTOR] FOREIGN KEY([TUTOR_ID])
REFERENCES [dbo].[SYS_USER] ([USER_ID])
GO
ALTER TABLE [dbo].[SYS_USER_TO_RATING] CHECK CONSTRAINT [FK_SYS_USER_TO_RATING_SYS_USER_TUTOR]
GO
ALTER TABLE [dbo].[SYS_USER_TO_SPECIALITY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_TO_SPECIALITY_SYS_EDU_LEVEL] FOREIGN KEY([EDU_LEVEL_ID])
REFERENCES [dbo].[SYS_EDU_LEVEL] ([EDU_LEVEL_ID])
GO
ALTER TABLE [dbo].[SYS_USER_TO_SPECIALITY] CHECK CONSTRAINT [FK_SYS_USER_TO_SPECIALITY_SYS_EDU_LEVEL]
GO
ALTER TABLE [dbo].[SYS_USER_TO_SPECIALITY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_USER_TO_SPECIALITY_SYS_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[SYS_USER] ([USER_ID])
GO
ALTER TABLE [dbo].[SYS_USER_TO_SPECIALITY] CHECK CONSTRAINT [FK_SYS_USER_TO_SPECIALITY_SYS_USER]
GO
